ip_forward: true
network_compression_threshold: 256
stats: 985b6546-0c6c-480b-95b3-62d2740eba1a
permissions:
  default:
  - bedwars.bedwars
groups:
  md_5:
  - default
servers:
  lobby:
    address: 127.0.0.1:25566
    restricted: false
    motd: |
      &a                   Hypixel Bedwars &c[1.8-1.14]
      &e&l          HYPIXEL BEDWARS GAME V3.0  &7by Ram
  bedwarsxp-1:
    address: 127.0.0.1:10001
    restricted: false
    motd: '&7'
  bedwarsxp-2:
    address: 127.0.0.1:10002
    restricted: false
    motd: '&7'
  bedwarsxp-3:
    address: 127.0.0.1:10003
    restricted: false
    motd: '&7'
  bedwarsxp-4:
    address: 127.0.0.1:10004
    restricted: false
    motd: '&7'
  bedwarsxp-5:
    address: 127.0.0.1:10005
    restricted: false
    motd: '&7'
  bedwarsxp-6:
    address: 127.0.0.1:10006
    restricted: false
    motd: '&7'
  bedwars-1:
    address: 127.0.0.1:20001
    restricted: false
    motd: '&7'
  bedwars-2:
    address: 127.0.0.1:20002
    restricted: false
    motd: '&7'
  bedwars-3:
    address: 127.0.0.1:20003
    restricted: false
    motd: '&7'
  bedwars-4:
    address: 127.0.0.1:20004
    restricted: false
    motd: '&7'
  bedwars-5:
    address: 127.0.0.1:20005
    restricted: false
    motd: '&7'
  bedwars-6:
    address: 127.0.0.1:20006
    restricted: false
    motd: '&7'
timeout: 30000
listeners:
- max_players: 30000
  host: 0.0.0.0:25565
  bind_local_address: false
  ping_passthrough: false
  tab_list: GLOBAL_PING
  forced_hosts:
    112315.pw: lobby
  tab_size: 60
  force_default_server: true
  motd: ''
  query_enabled: false
  query_port: 25563
  priorities:
  - lobby
  proxy_protocol: false
prevent_proxy_connections: false
player_limit: 500
online_mode: false
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 1
